global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  - job_name: 'api_metrics'
    static_configs:
      - targets: ['host.docker.internal:8000'] # если API экспортирует метрики через endpoint